### PR TITLE
feat: add bid method with selling coin denom for fixed price auction

### LINKED ISSUE #129: feat: add new bid way with selling coins for fixed price auction
## Summary

The current fixed price auction gets the bids having bid coin with paying coin denom.
In order to provide more flexibility, we consider a new case that a bidder places a bid with bid coin in selling coin denom.

## Problem Definition

The current fixed price auction restricts a bid to have bid coin with paying coin denom and sometime this can be non-intuitive.

## Proposal
- For fixed price auction, a bidder can place bid with bid coin in either paying coin denom or selling coin denom.
- This is not to introduce explicit additional bid type for fixed price auction. 

## Tasks

- Modify related codes 

## References

-
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

### PR DESCRIPTION
**Pull request by jeonghoyeo7**
## Description

closes: #129 

## Tasks

- [x] Add the feature to allow a bidder to place a bid with `SellingCoinDenom` for fixed price auction
- [x] Add a test case of incorrect coin denom for fixed price auction
- [x] Change the name `IsWinner` to `IsMatched`
- [x] Change the name `exchangedSellingAmount` to `bidSellingAmount`

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Appropriate labels applied
- [ ] Targeted PR against correct branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://go.dev/blog/godoc).
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

File: x/fundraising/client/cli/flags.go [hunk 1]
```diff
@@ -10,7 +10,7 @@ const (
 	FlagAuctionStatus = "status"
 	FlagAuctionType   = "type"
 	FlagBidderAddr    = "bidder-addr"
-	FlagIsWinner      = "is_winner"
+	FlagIsMatched     = "is_matched"
```
Comment (jaybxyz) [inline x/fundraising/client/cli/flags.go]: This flag was incorrect in the first place. Let's use dash instead of underscore.
```suggestion
	FlagIsMatched     = "is-matched"
```

File: x/fundraising/client/cli/flags.go [hunk 2]
```diff
@@ -28,7 +28,7 @@ func flagSetBids() *flag.FlagSet {
 	fs := flag.NewFlagSet("", flag.ContinueOnError)
 
 	fs.String(FlagBidderAddr, "", "The bech32 address of the bidder account")
-	fs.String(FlagIsWinner, "", "The eligibility of the bidder to purchase the selling coin")
+	fs.String(FlagIsMatched, "", "The eligibility of the bidder to purchase the selling coin")
```
Comment (jaybxyz) [inline x/fundraising/client/cli/flags.go]: This description may mislead bidders. Should we update the comment? 

Something like the following:

> The bid that successfully matched (a.k.a., winner)

File: x/fundraising/client/cli/query.go [hunk 3]
```diff
@@ -199,7 +199,7 @@ $ %s query %s bids 1 --winner
 			}
 
 			bidderAddr, _ := cmd.Flags().GetString(FlagBidderAddr)
-			eligible, _ := cmd.Flags().GetString(FlagIsWinner)
+			eligible, _ := cmd.Flags().GetString(FlagIsMatched)
```
Comment (jaybxyz) [inline x/fundraising/client/cli/query.go]:
```suggestion
			isMatched, _ := cmd.Flags().GetString(FlagIsMatched)
```

File: x/fundraising/client/cli/query.go [hunk 4]
```diff
@@ -215,7 +215,7 @@ $ %s query %s bids 1 --winner
 			req := &types.QueryBidsRequest{
 				AuctionId:  auctionId,
 				Bidder:     bidderAddr,
-				IsWinner:   eligible,
+				IsMatched:  eligible,
```
Comment (jaybxyz) [inline x/fundraising/client/cli/query.go]:
```suggestion
				IsMatched:  isMatched,
```

File: x/fundraising/types/bid.go [hunk 5]
```diff
@@ -12,10 +12,18 @@ func (b Bid) GetBidder() sdk.AccAddress {
...
+func (b Bid) GetBidSellingAmount(denom string) sdk.Int {
+	var bidSellingAmt sdk.Int
+
+	if b.Coin.Denom == denom {
+		bidSellingAmt = b.Coin.Amount.ToDec().QuoTruncate(b.Price).TruncateInt()
+	} else {
+		bidSellingAmt = b.Coin.Amount
+	}
+
+	return bidSellingAmt
```
Comment (jaybxyz) [inline x/fundraising/types/bid.go]: Is there use case when this function received the selling coin denom? If not, let's update the `denom` to `payingCoinDenom` to improve readability.
```suggestion
func (b Bid) GetBidSellingAmount(payingCoinDenom string) sdk.Int {
	var bidSellingAmt sdk.Int

	if b.Coin.Denom == payingCoinDenom {
		bidSellingAmt = b.Coin.Amount.ToDec().QuoTruncate(b.Price).TruncateInt()
	} else {
		bidSellingAmt = b.Coin.Amount
	}

	return bidSellingAmt
```

**Review by jaybxyz — CHANGES_REQUESTED** [review]
Can you update [this CLI description as well](https://github.com/tendermint/fundraising/blob/main/x/fundraising/client/cli/query.go#L188 
)?

File: x/fundraising/client/cli/flags.go (hunk 1 above)
Comment (jeonghoyeo7) [reply x/fundraising/client/cli/flags.go]: I changed as suggested.

File: x/fundraising/client/cli/flags.go (hunk 2 above)
Comment (jeonghoyeo7) [reply x/fundraising/client/cli/flags.go]: I changed as suggested.

File: x/fundraising/client/cli/query.go (hunk 3 above)
Comment (jeonghoyeo7) [reply x/fundraising/client/cli/query.go]: I changed as suggested.

File: x/fundraising/client/cli/query.go (hunk 4 above)
Comment (jeonghoyeo7) [reply x/fundraising/client/cli/query.go]: I changed as suggested.

File: x/fundraising/types/bid.go (hunk 5 above)
Comment (jeonghoyeo7) [reply x/fundraising/types/bid.go]: I changed as suggested.

**Comment by jaybxyz** [comment]
Can you update [this CLI description as well](https://github.com/tendermint/fundraising/blob/main/x/fundraising/client/cli/query.go#L188)? @jeonghoyeo7

**Review by jaybxyz — APPROVED** [review]
