### PR TITLE
fix: misleading error messages

### LINKED ISSUE #131: Fix error message that is misleading
## Summary

The following return error message is misleading. It sounds like the end time must be before the current time.

https://github.com/tendermint/fundraising/blob/main/x/fundraising/keeper/auction.go#L129
https://github.com/tendermint/fundraising/blob/main/x/fundraising/keeper/auction.go#L195

## Proposal

Read through other error messages that are misleading and not intuitive.

### PR DESCRIPTION
**Pull request by jaybxyz**
## Description

closes: #131

## Tasks

- [x] Fix to `end time must be set after the current time`
- [x] Clean up some codebase
- [x] Add more test cases to cover untouched logics
- [x] Split `Calculatexxx` logic to `match.go` file since `auction_test.go` is having too many functions to test
- [x] Use lower cases for variables in calculation test cases

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Appropriate labels applied
- [ ] Targeted PR against correct branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://go.dev/blog/godoc).
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

File: x/fundraising/keeper/match_test.go [hunk 1]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().Equal(mInfo.MatchedPrice, parseDec("0.9"))
+	s.Require().Equal(mInfo.TotalMatchedAmount, sdk.NewInt(1000_000_000))
+	s.Require().Equal(mInfo.AllocationMap[s.addr(1).String()], sdk.NewInt(500_000_000))
+	s.Require().Equal(mInfo.AllocationMap[s.addr(2).String()], sdk.NewInt(500_000_000))
+	s.Require().Equal(mInfo.AllocationMap[s.addr(3).String()], sdk.NewInt(0))
+	s.Require().Equal(mInfo.ReservedMatchedMap[s.addr(1).String()], sdk.NewInt(450_000_000))
+	s.Require().Equal(mInfo.ReservedMatchedMap[s.addr(2).String()], sdk.NewInt(450_000_000))
+	s.Require().Equal(mInfo.ReservedMatchedMap[s.addr(3).String()], sdk.NewInt(0))
+	s.Require().Equal(mInfo.RefundMap[s.addr(1).String()], sdk.NewInt(50_000_000))
+	s.Require().Equal(mInfo.RefundMap[s.addr(2).String()].Abs(), sdk.NewInt(0).Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]: As discussed, rather than comparing the absolute values, it would be better to use other function to compare zeros.

```suggestion
	s.Require().True(mInfo.RefundMap[s.addr(2).String()].IsZero())
```

File: x/fundraising/keeper/match_test.go [hunk 2]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().Equal(mInfo.RefundMap[s.addr(3).String()], sdk.NewInt(400_000_000))
+
+	// Distribute selling coin
+	err := s.keeper.AllocateSellingCoin(s.ctx, auction, mInfo)
+	s.Require().NoError(err)
+
+	s.Require().Equal(s.getBalance(auction.GetSellingReserveAddress(), auction.SellingCoin.Denom).Amount.Abs(), auction.SellingCoin.Amount.Sub(mInfo.TotalMatchedAmount).Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]: Similar to the above, rather than comparing the absolute values, it would be better to use other function to compare zeros.

```suggestion
	s.Require().True(s.getBalance(auction.GetSellingReserveAddress(), auction.SellingCoin.Denom).Amount.Equal(auction.SellingCoin.Amount.Sub(mInfo.TotalMatchedAmount)))
```

File: x/fundraising/keeper/match_test.go [hunk 3]
```diff
@@ -0,0 +1,1219 @@
...
+
+	err = s.keeper.ReleaseRemainingSellingCoin(s.ctx, auction)
+	s.Require().NoError(err)
+
+	// The selling reserve account balance must be zero
+	s.Require().True(s.getBalance(auction.GetSellingReserveAddress(), auction.SellingCoin.Denom).IsZero())
+
+	// The auctioneer must have sellingCoin.Amount - TotalMatchedAmount
+	s.Require().Equal(s.getBalance(s.addr(0), auction.GetSellingCoin().Denom).Amount, auction.SellingCoin.Amount.Sub(mInfo.TotalMatchedAmount).Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]: Same as above,

```suggestion
	s.Require().True(s.getBalance(s.addr(0), auction.GetSellingCoin().Denom).Amount.Equal(, auction.SellingCoin.Amount.Sub(mInfo.TotalMatchedAmount)))
```

File: x/fundraising/keeper/match_test.go [hunk 4]
```diff
@@ -0,0 +1,1219 @@
...
+	matchingPrice := parseDec("0.9")
+	matchedAmt := sdk.NewInt(500_000_000).ToDec().QuoTruncate(matchingPrice).TruncateInt()
+
+	s.Require().Equal(mInfo.TotalMatchedAmount, matchedAmt.Add(matchedAmt))
+	s.Require().Equal(mInfo.AllocationMap[s.addr(1).String()], matchedAmt)
+	s.Require().Equal(mInfo.AllocationMap[s.addr(2).String()], matchedAmt)
+	s.Require().Equal(mInfo.AllocationMap[s.addr(3).String()], sdk.NewInt(0))
+	s.Require().Equal(mInfo.ReservedMatchedMap[s.addr(1).String()], sdk.NewInt(500_000_000))
+	s.Require().Equal(mInfo.ReservedMatchedMap[s.addr(2).String()], sdk.NewInt(500_000_000))
+	s.Require().Equal(mInfo.ReservedMatchedMap[s.addr(3).String()], sdk.NewInt(0))
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go:119]: Same as above.

```suggestion
	s.Require().True(mInfo.ReservedMatchedMap[s.addr(3).String()].IsZero())
```

File: x/fundraising/keeper/match_test.go [hunk 5]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().Equal(mInfo.RefundMap[s.addr(1).String()].Abs(), sdk.NewInt(0).Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]: Same as above.

```suggestion
	s.Require().True(mInfo.RefundMap[s.addr(1).String()].IsZero())
```

File: x/fundraising/keeper/match_test.go [hunk 6]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().Equal(mInfo.RefundMap[s.addr(2).String()].Abs(), sdk.NewInt(0).Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]: Same as above.

```suggestion
	s.Require().True(mInfo.RefundMap[s.addr(2).String()].IsZero())
```

File: x/fundraising/keeper/match_test.go [hunk 7]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().NoError(err)
+
+	err = s.keeper.ReleaseRemainingSellingCoin(s.ctx, auction)
+	s.Require().NoError(err)
+
+	// The selling reserve account balance must be zero
+	s.Require().True(s.getBalance(auction.GetSellingReserveAddress(), auction.SellingCoin.Denom).IsZero())
+
+	// The auctioneer must have sellingCoin.Amount - TotalMatchedAmount
+	s.Require().Equal(s.getBalance(s.addr(0), auction.GetSellingCoin().Denom).Amount, auction.SellingCoin.Amount.Sub(mInfo.TotalMatchedAmount).Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]: Same as above.

```suggestion
	s.Require().True(s.getBalance(s.addr(0), auction.GetSellingCoin().Denom).Amount.Equal(auction.SellingCoin.Amount.Sub(mInfo.TotalMatchedAmount)))
```

File: x/fundraising/keeper/match_test.go [hunk 8]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().Equal(mInfo.MatchedLen, int64(2))
+	s.Require().Equal(mInfo.MatchedPrice, parseDec("0.9"))
+	matchingPrice := parseDec("0.9")
+	matchedAmt1 := sdk.NewInt(500_000_000)
+	matchedAmt2 := sdk.NewInt(500_000_000).ToDec().QuoTruncate(matchingPrice).TruncateInt()
+
+	s.Require().Equal(mInfo.TotalMatchedAmount, sdk.NewInt(500_000_000).Add(matchedAmt2))
+	s.Require().Equal(mInfo.AllocationMap[s.addr(1).String()], matchedAmt1)
+	s.Require().Equal(mInfo.AllocationMap[s.addr(2).String()], matchedAmt2)
+	s.Require().Equal(mInfo.AllocationMap[s.addr(3).String()], sdk.NewInt(0))
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go:185]: Same as above.

```suggestion
	s.Require().True(mInfo.AllocationMap[s.addr(3).String()].IsZero())
```

File: x/fundraising/keeper/match_test.go [hunk 9]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().Equal(mInfo.ReservedMatchedMap[s.addr(1).String()], sdk.NewInt(450_000_000))
+	s.Require().Equal(mInfo.ReservedMatchedMap[s.addr(2).String()], sdk.NewInt(500_000_000))
+	s.Require().Equal(mInfo.ReservedMatchedMap[s.addr(3).String()], sdk.NewInt(0))
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go:188]: Same as above.

```suggestion
	s.Require().True(mInfo.ReservedMatchedMap[s.addr(3).String()].IsZero())
```

File: x/fundraising/keeper/match_test.go [hunk 10]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().Equal(mInfo.RefundMap[s.addr(1).String()], sdk.NewInt(50_000_000))
+	s.Require().Equal(mInfo.RefundMap[s.addr(2).String()].Abs(), sdk.NewInt(0).Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]: Same as above.

```suggestion
	s.Require().True(mInfo.RefundMap[s.addr(2).String()].IsZero())
```

File: x/fundraising/keeper/match_test.go [hunk 11]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().NoError(err)
+
+	err = s.keeper.ReleaseRemainingSellingCoin(s.ctx, auction)
+	s.Require().NoError(err)
+
+	// The selling reserve account balance must be zero
+	s.Require().True(s.getBalance(auction.GetSellingReserveAddress(), auction.SellingCoin.Denom).IsZero())
+
+	// The auctioneer must have sellingCoin.Amount - TotalMatchedAmount
+	s.Require().Equal(s.getBalance(s.addr(0), auction.GetSellingCoin().Denom).Amount, auction.SellingCoin.Amount.Sub(mInfo.TotalMatchedAmount).Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]: Same as above.

```suggestion
	s.Require().True(s.getBalance(s.addr(0), auction.GetSellingCoin().Denom).Amount.Equal(auction.SellingCoin.Amount.Sub(mInfo.TotalMatchedAmount)))
```

File: x/fundraising/keeper/match_test.go [hunk 12]
```diff
@@ -0,0 +1,1219 @@
...
+
+	mInfo := s.keeper.CalculateBatchAllocation(s.ctx, a)
+
+	// Checking
+	s.Require().Equal(mInfo.MatchedLen, int64(2))
+	s.Require().Equal(mInfo.MatchedPrice, parseDec("0.9"))
+	s.Require().Equal(mInfo.TotalMatchedAmount, sdk.NewInt(800_000_000))
+	s.Require().Equal(mInfo.AllocationMap[s.addr(1).String()], sdk.NewInt(400_000_000))
+	s.Require().Equal(mInfo.AllocationMap[s.addr(2).String()], sdk.NewInt(400_000_000))
+	s.Require().Equal(mInfo.AllocationMap[s.addr(3).String()], sdk.NewInt(0))
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go:250]: Same as above.

```suggestion
	s.Require().True(mInfo.AllocationMap[s.addr(3).String()].IsZero())
```

File: x/fundraising/keeper/match_test.go [hunk 13]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().Equal(mInfo.ReservedMatchedMap[s.addr(1).String()], sdk.NewInt(360_000_000))
+	s.Require().Equal(mInfo.ReservedMatchedMap[s.addr(2).String()], sdk.NewInt(360_000_000))
+	s.Require().Equal(mInfo.ReservedMatchedMap[s.addr(3).String()], sdk.NewInt(0))
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go:253]: Same as above.

```suggestion
	s.Require().True(mInfo.ReservedMatchedMap[s.addr(3).String()].IsZero())
```

File: x/fundraising/keeper/match_test.go [hunk 14]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().Equal(mInfo.RefundMap[s.addr(1).String()], sdk.NewInt(40_000_000))
+	s.Require().Equal(mInfo.RefundMap[s.addr(2).String()].Abs(), sdk.NewInt(0).Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]: Same as above.

```suggestion
	s.Require().True(mInfo.RefundMap[s.addr(2).String()].IsZero())
```

File: x/fundraising/keeper/match_test.go [hunk 15]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().Equal(mInfo.TotalMatchedAmount, sdk.NewInt(1200_000_000))
+	s.Require().Equal(mInfo.AllocationMap[s.addr(1).String()], sdk.NewInt(400_000_000))
+	s.Require().Equal(mInfo.AllocationMap[s.addr(2).String()], sdk.NewInt(400_000_000))
+	s.Require().Equal(mInfo.AllocationMap[s.addr(3).String()], sdk.NewInt(400_000_000))
+	s.Require().Equal(mInfo.ReservedMatchedMap[s.addr(1).String()], sdk.NewInt(320_000_000))
+	s.Require().Equal(mInfo.ReservedMatchedMap[s.addr(2).String()], sdk.NewInt(320_000_000))
+	s.Require().Equal(mInfo.ReservedMatchedMap[s.addr(3).String()], sdk.NewInt(320_000_000))
+	s.Require().Equal(mInfo.RefundMap[s.addr(1).String()], sdk.NewInt(80_000_000))
+	s.Require().Equal(mInfo.RefundMap[s.addr(2).String()], sdk.NewInt(40_000_000))
+	s.Require().Equal(mInfo.RefundMap[s.addr(3).String()].Abs(), sdk.NewInt(0_000_000).Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]: Same as above.

```suggestion
	s.Require().True(mInfo.RefundMap[s.addr(3).String()].IsZero())
```

File: x/fundraising/keeper/match_test.go [hunk 16]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().Equal(mInfo.TotalMatchedAmount, sdk.NewInt(1662_500_000))
+	s.Require().Equal(mInfo.AllocationMap[s.addr(1).String()], sdk.NewInt(500_000_000))
+	s.Require().Equal(mInfo.AllocationMap[s.addr(2).String()], sdk.NewInt(600_000_000))
+	s.Require().Equal(mInfo.AllocationMap[s.addr(3).String()], sdk.NewInt(562_500_000))
+	s.Require().Equal(mInfo.ReservedMatchedMap[s.addr(1).String()], sdk.NewInt(400_000_000))
+	s.Require().Equal(mInfo.ReservedMatchedMap[s.addr(2).String()], sdk.NewInt(480_000_000))
+	s.Require().Equal(mInfo.ReservedMatchedMap[s.addr(3).String()], sdk.NewInt(450_000_000))
+	s.Require().Equal(mInfo.RefundMap[s.addr(1).String()], sdk.NewInt(100_000_000))
+	s.Require().Equal(mInfo.RefundMap[s.addr(2).String()], sdk.NewInt(20_000_000))
+	s.Require().Equal(mInfo.RefundMap[s.addr(3).String()].Abs(), sdk.NewInt(0).Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]: Same as above.

```suggestion
	s.Require().True(mInfo.RefundMap[s.addr(3).String()].IsZero())
```

File: x/fundraising/keeper/match_test.go [hunk 17]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().NoError(err)
+
+	err = s.keeper.ReleaseRemainingSellingCoin(s.ctx, auction)
+	s.Require().NoError(err)
+
+	// The selling reserve account balance must be zero
+	s.Require().True(s.getBalance(auction.GetSellingReserveAddress(), auction.SellingCoin.Denom).IsZero())
+
+	// The auctioneer must have sellingCoin.Amount - TotalMatchedAmount
+	s.Require().Equal(s.getBalance(s.addr(0), auction.GetSellingCoin().Denom).Amount.Abs(), sdk.NewInt(37_500_000).Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]: In order not to use Abs for comparison.

```suggestion
	s.Require().Equal(s.getBalance(s.addr(0), auction.GetSellingCoin().Denom).Amount, sdk.NewInt(37_500_000))
```

File: x/fundraising/keeper/match_test.go [hunk 18]
```diff
@@ -0,0 +1,1219 @@
...
+	refundAmt3 := sdk.NewInt(100_000_000)
+	refundAmt4 := sdk.NewInt(10_000_000)
+	refundAmt5 := sdk.NewInt(150_000_000)
+	refundAmt6 := sdk.NewInt(550_000_000)
+	refundAmt7 := sdk.NewInt(500_000_000)
+	refundAmt8 := sdk.NewInt(50_000_000)
+	refundAmt9 := sdk.NewInt(360_000_000)
+	refundAmt10 := sdk.NewInt(60_000_000)
+
+	s.Require().Equal(mInfo.RefundMap[s.addr(1).String()].Abs(), refundAmt1.Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]:
```suggestion
	s.Require().Equal(mInfo.RefundMap[s.addr(1).String()], refundAmt1)
```

File: x/fundraising/keeper/match_test.go [hunk 19]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().Equal(mInfo.RefundMap[s.addr(2).String()].Abs(), refundAmt2.Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]:
```suggestion
	s.Require().True(mInfo.RefundMap[s.addr(2).String()].IsZero())
```

File: x/fundraising/keeper/match_test.go [hunk 20]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().Equal(mInfo.RefundMap[s.addr(3).String()].Abs(), refundAmt3.Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]:
```suggestion
	s.Require().Equal(mInfo.RefundMap[s.addr(3).String()], refundAmt3)
```

File: x/fundraising/keeper/match_test.go [hunk 21]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().Equal(mInfo.RefundMap[s.addr(4).String()].Abs(), refundAmt4.Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]:
```suggestion
	s.Require().Equal(mInfo.RefundMap[s.addr(4).String()], refundAmt4)
```

File: x/fundraising/keeper/match_test.go [hunk 22]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().Equal(mInfo.RefundMap[s.addr(5).String()].Abs(), refundAmt5.Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]:
```suggestion
	s.Require().Equal(mInfo.RefundMap[s.addr(5).String()], refundAmt5)
```

File: x/fundraising/keeper/match_test.go [hunk 23]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().Equal(mInfo.RefundMap[s.addr(6).String()].Abs(), refundAmt6.Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]:
```suggestion
	s.Require().Equal(mInfo.RefundMap[s.addr(6).String()], refundAmt6)
```

File: x/fundraising/keeper/match_test.go [hunk 24]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().Equal(mInfo.RefundMap[s.addr(7).String()].Abs(), refundAmt7.Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]:
```suggestion
	s.Require().Equal(mInfo.RefundMap[s.addr(7).String()], refundAmt7)
```

File: x/fundraising/keeper/match_test.go [hunk 25]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().Equal(mInfo.RefundMap[s.addr(8).String()].Abs(), refundAmt8.Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]:
```suggestion
	s.Require().Equal(mInfo.RefundMap[s.addr(8).String()], refundAmt8)
```

File: x/fundraising/keeper/match_test.go [hunk 26]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().Equal(mInfo.RefundMap[s.addr(9).String()].Abs(), refundAmt9.Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]:
```suggestion
	s.Require().Equal(mInfo.RefundMap[s.addr(9).String()], refundAmt9)
```

File: x/fundraising/keeper/match_test.go [hunk 27]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().Equal(mInfo.RefundMap[s.addr(10).String()].Abs(), refundAmt10.Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]:
```suggestion
	s.Require().Equal(mInfo.RefundMap[s.addr(10).String()], refundAmt10)
```

File: x/fundraising/keeper/match_test.go [hunk 28]
```diff
@@ -0,0 +1,1219 @@
...
+	// The auctioneer must have sellingCoin.Amount - TotalMatchedAmount
+	s.Require().Equal(s.getBalance(s.addr(0), auction.GetSellingCoin().Denom).Amount, auction.SellingCoin.Amount.Sub(mInfo.TotalMatchedAmount))
+
+	// The bidders must have the matched selling coin
+	s.Require().Equal(s.getBalance(s.addr(1), auction.GetSellingCoin().Denom).Amount, matchedAmt1)
+	s.Require().Equal(s.getBalance(s.addr(2), auction.GetSellingCoin().Denom).Amount, matchedAmt2)
+	s.Require().Equal(s.getBalance(s.addr(3), auction.GetSellingCoin().Denom).Amount, matchedAmt3)
+	s.Require().Equal(s.getBalance(s.addr(4), auction.GetSellingCoin().Denom).Amount, matchedAmt4)
+	s.Require().Equal(s.getBalance(s.addr(5), auction.GetSellingCoin().Denom).Amount, matchedAmt5)
+	s.Require().Equal(s.getBalance(s.addr(6), auction.GetSellingCoin().Denom).Amount.Abs(), matchedAmt_Zero.Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]:
```suggestion
	s.Require().True(s.getBalance(s.addr(6), auction.GetSellingCoin().Denom).Amount.IsZero())
```

File: x/fundraising/keeper/match_test.go [hunk 29]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().Equal(s.getBalance(s.addr(7), auction.GetSellingCoin().Denom).Amount.Abs(), matchedAmt_Zero.Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]:
```suggestion
	s.Require().True(s.getBalance(s.addr(7), auction.GetSellingCoin().Denom).Amount.IsZero())
```

File: x/fundraising/keeper/match_test.go [hunk 30]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().Equal(s.getBalance(s.addr(8), auction.GetSellingCoin().Denom).Amount, matchedAmt8)
+	s.Require().Equal(s.getBalance(s.addr(9), auction.GetSellingCoin().Denom).Amount.Abs(), matchedAmt_Zero.Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]:
```suggestion
	s.Require().True(s.getBalance(s.addr(9), auction.GetSellingCoin().Denom).Amount.IsZero())
```

File: x/fundraising/keeper/match_test.go [hunk 31]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().Equal(s.getBalance(s.addr(10), auction.GetSellingCoin().Denom).Amount.Abs(), matchedAmt_Zero.Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]:
```suggestion
	s.Require().True(s.getBalance(s.addr(10), auction.GetSellingCoin().Denom).Amount.IsZero())
```

File: x/fundraising/keeper/match_test.go [hunk 32]
```diff
@@ -0,0 +1,1219 @@
...
+	refundAmt3 := sdk.NewInt(820_000_000)
+	refundAmt4 := sdk.NewInt(20_000_000)
+	refundAmt5 := sdk.NewInt(180_000_000)
+	refundAmt6 := sdk.NewInt(400_000_000)
+	refundAmt7 := sdk.NewInt(0)
+	refundAmt8 := sdk.NewInt(100_000_000)
+	refundAmt9 := sdk.NewInt(0)
+	refundAmt10 := sdk.NewInt(0)
+
+	s.Require().Equal(mInfo.RefundMap[s.addr(1).String()].Abs(), refundAmt1.Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]:
```suggestion
	s.Require().Equal(mInfo.RefundMap[s.addr(1).String()], refundAmt1)
```

File: x/fundraising/keeper/match_test.go [hunk 33]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().Equal(mInfo.RefundMap[s.addr(2).String()].Abs(), refundAmt2.Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]:
```suggestion
	s.Require().Equal(mInfo.RefundMap[s.addr(2).String()], refundAmt2)
```

File: x/fundraising/keeper/match_test.go [hunk 34]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().Equal(mInfo.RefundMap[s.addr(3).String()].Abs(), refundAmt3.Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]:
```suggestion
	s.Require().Equal(mInfo.RefundMap[s.addr(3).String()], refundAmt3)
```

File: x/fundraising/keeper/match_test.go [hunk 35]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().Equal(mInfo.RefundMap[s.addr(4).String()].Abs(), refundAmt4.Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]:
```suggestion
	s.Require().Equal(mInfo.RefundMap[s.addr(4).String()], refundAmt4)
```

File: x/fundraising/keeper/match_test.go [hunk 36]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().Equal(mInfo.RefundMap[s.addr(5).String()].Abs(), refundAmt5.Abs())
+	s.Require().Equal(mInfo.RefundMap[s.addr(6).String()].Abs(), refundAmt6.Abs())
+	s.Require().Equal(mInfo.RefundMap[s.addr(7).String()].Abs(), refundAmt7.Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]:
```suggestion
	s.Require().True(mInfo.RefundMap[s.addr(7).String()].IsZero())
```

File: x/fundraising/keeper/match_test.go [hunk 37]
```diff
@@ -0,0 +1,1219 @@
...
+	refundAmt7 := sdk.NewInt(0)
+	refundAmt8 := sdk.NewInt(100_000_000)
+	refundAmt9 := sdk.NewInt(0)
+	refundAmt10 := sdk.NewInt(0)
+
+	s.Require().Equal(mInfo.RefundMap[s.addr(1).String()].Abs(), refundAmt1.Abs())
+	s.Require().Equal(mInfo.RefundMap[s.addr(2).String()].Abs(), refundAmt2.Abs())
+	s.Require().Equal(mInfo.RefundMap[s.addr(3).String()].Abs(), refundAmt3.Abs())
+	s.Require().Equal(mInfo.RefundMap[s.addr(4).String()].Abs(), refundAmt4.Abs())
+	s.Require().Equal(mInfo.RefundMap[s.addr(5).String()].Abs(), refundAmt5.Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]:
```suggestion
	s.Require().Equal(mInfo.RefundMap[s.addr(5).String()], refundAmt5)
```

File: x/fundraising/keeper/match_test.go [hunk 38]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().Equal(mInfo.RefundMap[s.addr(6).String()].Abs(), refundAmt6.Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]:
```suggestion
	s.Require().Equal(mInfo.RefundMap[s.addr(6).String()], refundAmt6)
```

File: x/fundraising/keeper/match_test.go [hunk 39]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().Equal(mInfo.RefundMap[s.addr(7).String()].Abs(), refundAmt7.Abs())
+	s.Require().Equal(mInfo.RefundMap[s.addr(8).String()].Abs(), refundAmt8.Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]:
```suggestion
	s.Require().Equal(mInfo.RefundMap[s.addr(8).String()], refundAmt8)
```

File: x/fundraising/keeper/match_test.go [hunk 40]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().Equal(mInfo.RefundMap[s.addr(9).String()].Abs(), refundAmt9.Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]:
```suggestion
	s.Require().True(mInfo.RefundMap[s.addr(9).String()].IsZero())
```

File: x/fundraising/keeper/match_test.go [hunk 41]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().Equal(mInfo.RefundMap[s.addr(10).String()].Abs(), refundAmt10.Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]:
```suggestion
	s.Require().True(mInfo.RefundMap[s.addr(10).String()].IsZero())
```

File: x/fundraising/keeper/match_test.go [hunk 42]
```diff
@@ -0,0 +1,1219 @@
...
+	// The auctioneer must have sellingCoin.Amount - TotalMatchedAmount
+	s.Require().Equal(s.getBalance(s.addr(0), auction.GetSellingCoin().Denom).Amount, auction.SellingCoin.Amount.Sub(mInfo.TotalMatchedAmount))
+
+	// The bidders must have the matched selling coin
+	s.Require().Equal(s.getBalance(s.addr(1), auction.GetSellingCoin().Denom).Amount, matchedAmt1)
+	s.Require().Equal(s.getBalance(s.addr(2), auction.GetSellingCoin().Denom).Amount, matchedAmt2)
+	s.Require().Equal(s.getBalance(s.addr(3), auction.GetSellingCoin().Denom).Amount, matchedAmt3)
+	s.Require().Equal(s.getBalance(s.addr(4), auction.GetSellingCoin().Denom).Amount, matchedAmt4)
+	s.Require().Equal(s.getBalance(s.addr(5), auction.GetSellingCoin().Denom).Amount, matchedAmt5)
+	s.Require().Equal(s.getBalance(s.addr(6), auction.GetSellingCoin().Denom).Amount.Abs(), matchedAmt6.Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]:
```suggestion
	s.Require().True(s.getBalance(s.addr(6), auction.GetSellingCoin().Denom).Amount.Equal(matchedAmt6))
```

File: x/fundraising/keeper/match_test.go [hunk 43]
```diff
@@ -0,0 +1,1219 @@
...
+	refundAmt3 := sdk.NewInt(910_000_000)
+	refundAmt4 := sdk.NewInt(30_000_000)
+	refundAmt5 := sdk.NewInt(210_000_000)
+	refundAmt6 := sdk.NewInt(50_000_000)
+	refundAmt7 := sdk.NewInt(0)
+	refundAmt8 := sdk.NewInt(120_000_000)
+	refundAmt9 := sdk.NewInt(20_000_000)
+	refundAmt10 := sdk.NewInt(10_000_000)
+
+	s.Require().Equal(mInfo.RefundMap[s.addr(1).String()].Abs(), refundAmt1.Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]:
```suggestion
	s.Require().Equal(mInfo.RefundMap[s.addr(1).String()], refundAmt1)
```

File: x/fundraising/keeper/match_test.go [hunk 44]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().Equal(mInfo.RefundMap[s.addr(2).String()].Abs(), refundAmt2.Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]:
```suggestion
	s.Require().Equal(mInfo.RefundMap[s.addr(2).String()], refundAmt2)
```

File: x/fundraising/keeper/match_test.go [hunk 45]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().Equal(mInfo.RefundMap[s.addr(3).String()].Abs(), refundAmt3.Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]:
```suggestion
	s.Require().Equal(mInfo.RefundMap[s.addr(3).String()], refundAmt3)
```

File: x/fundraising/keeper/match_test.go [hunk 46]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().Equal(mInfo.RefundMap[s.addr(4).String()].Abs(), refundAmt4.Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]:
```suggestion
	s.Require().Equal(mInfo.RefundMap[s.addr(4).String()], refundAmt4)
```

File: x/fundraising/keeper/match_test.go [hunk 47]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().Equal(mInfo.RefundMap[s.addr(5).String()].Abs(), refundAmt5.Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]:
```suggestion
	s.Require().Equal(mInfo.RefundMap[s.addr(5).String()], refundAmt5)
```

File: x/fundraising/keeper/match_test.go [hunk 48]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().Equal(mInfo.RefundMap[s.addr(6).String()].Abs(), refundAmt6.Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]:
```suggestion
	s.Require().Equal(mInfo.RefundMap[s.addr(6).String()], refundAmt6)
```

File: x/fundraising/keeper/match_test.go [hunk 49]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().Equal(mInfo.RefundMap[s.addr(7).String()].Abs(), refundAmt7.Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]:
```suggestion
	s.Require().Ture(mInfo.RefundMap[s.addr(7).String()].Equal(refundAmt7))
```

File: x/fundraising/keeper/match_test.go [hunk 50]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().Equal(mInfo.RefundMap[s.addr(8).String()].Abs(), refundAmt8.Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]:
```suggestion
	s.Require().Equal(mInfo.RefundMap[s.addr(8).String()], refundAmt8)
```

File: x/fundraising/keeper/match_test.go [hunk 51]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().Equal(mInfo.RefundMap[s.addr(9).String()].Abs(), refundAmt9.Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]:
```suggestion
	s.Require().Equal(mInfo.RefundMap[s.addr(9).String()], refundAmt9)
```

File: x/fundraising/keeper/match_test.go [hunk 52]
```diff
@@ -0,0 +1,1219 @@
...
+	s.Require().Equal(mInfo.RefundMap[s.addr(10).String()].Abs(), refundAmt10.Abs())
```
Comment (jeonghoyeo7) [inline x/fundraising/keeper/match_test.go]:
```suggestion
	s.Require().Equal(mInfo.RefundMap[s.addr(10).String()], refundAmt10)
```
